name: Build Optimized RandomX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Build Assembly Code
      run: |
        nasm -f elf64 optimized_randomx.asm -o optimized_randomx.o
        ld optimized_randomx.o -o optimized_randomx

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: optimized_randomx
        path: optimized_randomx
